### ISSUE TITLE
Recipe image not shown (Add to Favorites, or Add to Week Meal Plan)

### ISSUE THREAD

**Issue by robchin89** [msalvi96/Prep_Your_Meal#16]
On Recipes Page,

When you click to add Favorites, it shows up in the Favorites page, but images are not included.

When you click to add to a specific day (i.e. Mon, Tues, Wed... Sun), it shows up in the Planner page (for proper day), but images are not included.

In either page, clicking the Recipe's "View Details", also redirects to error.

**Comment by fitrepoz** [comment]
image url not included in api, I did add a placeholder image for now
