### ISSUE TITLE
Adding Ingredients Page (Ingredient Name)

### ISSUE THREAD

**Issue by robchin89** [msalvi96/Prep_Your_Meal#24]
Sometimes the name of the ingredient is not viewable fully.

For example, yellow onions is shown as "yellow o..."

**Comment by fitrepoz** [comment]
I shortened this on purpose to keep the boxes the same size. We can change if we want but they will all vary in size.

**Comment by robchin89** [comment]
Latest commit changes the layout of the ingredients page
